name: practice-pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set-up-julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'  # Use your preferred version

      - name: install-dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

      - name: export-notebooks
        run: julia --project=@. scripts/export.jl

      - name: deploy-to-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true  # Optional: Preserve existing files in gh-pages
